### PR TITLE
forward IO errors to curl

### LINKED ISSUE #186: fails to handle broken connections?
I was on a branch doing some IO work, so this could be my fault, but I noticed that this line: https://github.com/JuliaLang/Downloads.jl/blob/c12b62647da1eb5db7cc0fcf6f618c1a8c54a6e8/src/Curl/Multi.jl#L168
does not appear to handle the possibility of IO faults. In particular, I observed this result in CI:
```
From worker 36:   UNHANDLED TASK ERROR: IOError: FDWatcher: bad file descriptor (EBADF)
From worker 36:   Stacktrace:
From worker 36:    [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
From worker 36:      @ Base ./task.jl:877
From worker 36:    [2] wait()
From worker 36:      @ Base ./task.jl:941
From worker 36:    [3] wait(c::Base.GenericCondition{Base.Threads.SpinLock})
From worker 36:      @ Base ./condition.jl:124
From worker 36:    [4] _wait(fdw::FileWatching._FDWatcher, mask::FileWatching.FDEvent)
From worker 36:      @ FileWatching /data/vtjnash/julia1/usr/share/julia/stdlib/v1.9/FileWatching/src/FileWatching.jl:556
From worker 36:    [5] wait(fdw::FileWatching.FDWatcher)
From worker 36:      @ FileWatching /data/vtjnash/julia1/usr/share/julia/stdlib/v1.9/FileWatching/src/FileWatching.jl:584
From worker 36:    [6] macro expansion
From worker 36:      @ /data/vtjnash/julia1/usr/share/julia/stdlib/v1.9/Downloads/src/Curl/Multi.jl:166 [inlined]
From worker 36:    [7] (::Downloads.Curl.var"#40#46"{Int32, FileWatching.FDWatcher, Downloads.Curl.Multi})()
From worker 36:      @ Downloads.Curl ./task.jl:490
download                                 (36) |     4.54 |   0.00 |  0.0 |       9.95 |  2246.62
```
This is actually the only error that can possibly occur here (on unix), as we see here
https://github.com/libuv/libuv/blob/1fe609ea05ab37298fdfd34eed63647493002abb/src/unix/poll.c#L47-L52
and thus occurs almost exclusively in the case where you got an RST packet and need to make sure the rest of the connection content gets destroyed (it can be mapped to readable|writable, and let the next read handle it).

### PR DESCRIPTION
**Pull request by vtjnash**
Maybe like this?

Fixes #186

### CODE REVIEW

File: src/Curl/Multi.jl [hunk 1]
```diff
@@ -163,14 +163,16 @@ function socket_callback(
...
         @check curl_multi_assign(multi.handle, sock, watcher_p)
         task = @async while watcher.readable || watcher.writable # isopen(watcher)
-            events = try wait(watcher)
+            events = try
+                wait(watcher)
             catch err
                 err isa EOFError && return
-                rethrow()
+                err isa Base.IOError || rethrow()
+                FileWatching.FDEvent()
```
Comment (StefanKarpinski) [inline src/Curl/Multi.jl:171]: I don't quite understand what this does. Can you explain? Also, it would be great to get a test that exercises this code somehow. I'm not sure how to trigger this error, less so how to trigger both error code paths.

Comment (vtjnash) [reply src/Curl/Multi.jl:171]: It constructs and empty FDEvent object (timeout=true) and assigns it to the `events` variable. You would need to convince the remote server to send an RST over the connection. That is tricky since most environments do not allow you to do that explicitly, but only in response to the other client making an protocol error (for example, libuv only gained that functionality last year)

Comment (StefanKarpinski) [reply src/Curl/Multi.jl:171]: Should this return an empty events variable or should it set `events.disconnect`? Alternately, this code path could just set `flags = CURL_CSELECT_ERR` directly and skip constructing a dummy `events` object.

Comment (vtjnash) [reply src/Curl/Multi.jl:171]: It is not a disconnect (disconnect would map to isreadable, since it notifies you there is a pending change in the `read` state), while this signals a change to the error state (though the actual change can also be determined by calling `read`)

Comment (vtjnash) [reply src/Curl/Multi.jl:171]: An events object is just an `int` register, so there is nothing really to construct
