### PR TITLE
dont set Curl option TCP_FASTOPEN

### LINKED ISSUE #36: Downloading files with FTP protocol fails with `Could not resolve host`
Julia v1.5:
```
julia> download("ftp://xmlsoft.org/libxslt/libxslt-1.1.33.tar.gz")
"/tmp/jl_PhxwJQ"
```

with `Downloads`:
```
julia> Downloads.download("ftp://xmlsoft.org/libxslt/libxslt-1.1.33.tar.gz")
ERROR: Could not resolve host: 
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] (::Downloads.var"#2#3"{Vector{Pair{String, String}}, Downloads.Downloader, String})(io::IOStream)
   @ Downloads ~/repo/julia/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:69
 [3] arg_write(f::Downloads.var"#2#3"{Vector{Pair{String, String}}, Downloads.Downloader, String}, arg::Nothing)
   @ ArgTools ~/repo/julia/usr/share/julia/stdlib/v1.6/ArgTools/src/ArgTools.jl:101
 [4] #download#1
   @ ~/repo/julia/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:49 [inlined]
 [5] download
   @ ~/repo/julia/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:48 [inlined]
 [6] top-level scope
   @ REPL[8]:1
```

### PR DESCRIPTION
**Pull request by KlausC**
fixes #36

### CODE REVIEW

**Comment by giordano** [comment]
Maybe add tests in #45?

**Comment by KlausC** [comment]
An upstream bug has been reported here: https://github.com/curl/curl/issues/6252

**Comment by StefanKarpinski** [comment]
Setting TCP_FASTOPEN significantly speeds up HTTP downloads. Perhaps this should be changed to only not set TCP_FASTOPEN when doing an FTP download on Linux since that's the only place where this causes issues?

**Comment by StefanKarpinski** [comment]
Or if we're not going to set the option, it would be better to just delete the call entirely since not setting it is the default and in general using the default should be safe.

Thanks a lot for finding the cause of this problem, by the way!

File: src/Curl/Easy.jl [hunk 1]
```diff
@@ -44,7 +44,7 @@ end
 
 function set_defaults(easy::Easy)
     # curl options
-    curl_easy_setopt(easy.handle, CURLOPT_TCP_FASTOPEN, true) # failure ok, unsupported
+    curl_easy_setopt(easy.handle, CURLOPT_TCP_FASTOPEN, false) # upstream error
```
Comment (StefanKarpinski) [inline src/Curl/Easy.jl:47]:
```suggestion
```
If we're not going to set the option, we can just delete this line entirely.

File: test/runtests.jl [hunk 2]
```diff
@@ -382,5 +382,13 @@ include("setup.jl")
     end
 end
 
+@testset "ftp download" begin
```
Comment (StefanKarpinski) [inline test/runtests.jl:385]:
```suggestion
@__MODULE__ == Main && @testset "ftp download" begin
```
This will not run this test suite during Julia CI (which generates an anonymous module that it runs each test suite in). It's fine to use a random FTP server for CI for this package by itself but Julia CI runs so much that it will surely cause problems and flakiness.

**Review by StefanKarpinski — CHANGES_REQUESTED** [review]

**Review by StefanKarpinski — APPROVED** [review]
I have applied the changes that I requested. Will merge when CI passes.

**Comment by KlausC** [comment]
> An upstream bug has been reported here: [curl/curl#6252](https://github.com/curl/curl/issues/6252)

As of 2020/12/6 upstream fix has been merged into master. Will probably be in coming release curl-7.74

**Comment by StefanKarpinski** [comment]
👍🏻 I'm also following those issues — thanks for making the upstream fix! If you happen to notice when the release is made, ping me and I'll see about making this set `TCP_FASTOPEN` if the libcurl version is new enough.

**Comment by KlausC** [comment]
The upstream project issued release 7.74 recently, including the fix mentioned above.

 https://curl.se/download.html
